# Outlier handling (from EDA)
outlier_caps:
  Amount: 1000000 # UGX (99th percentile)

# Feature engineering
features:
  numeric: ["Amount", "Value", "Recency", "Frequency", "Monetary"]
  categorical: ["ProductCategory", "ChannelId"]

# RFM parameters
rfm:
  snapshot_date: "2019-12-31" # Cutoff date for Recency

# Risk clustering parameters
risk_model:
  n_clusters: 3
  risk_cluster: 0 # Index of high-risk cluster
# Model training parameters
model_training:
  test_size: 0.2
  random_state: 42
  hyperopt_evals: 20
